version: '3.9'

services:
  web:
    build: ../
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ../.env
    image: backend
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - db

  celery:
    command: celery -A habr_parser worker -B --loglevel=info -E
    env_file:
      - ../.env
    networks:
      - default
    depends_on:
      - web
      - redis
    image: backend
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: [ sh, -c, "rm -f /data/dump.rdb && redis-server" ]
    ports:
      - 6379:6379
    restart: unless-stopped

  db:
    image: postgres:16.2-bullseye
    volumes:
      - postgres_habr_data:/var/lib/postgresql/data/:z
    env_file:
      - ../.env
    ports:
      - 5432:5432


volumes:
  postgres_habr_data: