# Generated by Django 5.0.3 on 2024-03-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('url', models.URLField()),
                ('author_name', models.CharField()),
                ('author_link', models.URLField()),
                ('publish_date', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
    ]
