# Generated by Django 5.0.3 on 2024-03-06 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='hub',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='parser.hub'),
            preserve_default=False,
        ),
    ]
